#!/bin/bash
Person1="Russia"
Person2="Ukraine"
BASH="air strike"
echo"$Person1: $Person2 i will $BASH you to the stone age"
echo "$Person2: We will $BASH you to the stone age too"
echo "$Person1: I will $BASH you to the stone age again"
echo "$Person2: We will $BASH you to the stone age again too"
echo "$Person1: I will $BASH you to the stone age again and again"
echo"$Person2: we will stop harmozgan and $BASH you to the stone age again and again"
echo "$Person1: I will $BASH you to the stone age again and again and again"
echo "$Person2: We will $BASH you to the stone age again and again and again too"
echo "$Person1: I will $BASH you to the stone age again and again and again and again"
echo "$Person2: We will $BASH you to the stone age again and again and again and again too"
echo "$Person1: I will $BASH you to the stone age again and again and again and again and again"
echo "$Person2: We will $BASH you to the stone age again and again and again and again and again too"
echo "$Person1: I will $BASH you to the stone age again and again and again and again and again and again"
echo "$Person2: We will $BASH you to the stone age again and again and again and again and again and again too"
echo "$Person1: I will $BASH you to the stone age again and again and again and again and again and again and again"
sleep 5
echo "$Person2: We will $BASH you to the stone age again and again and again and again and again and again and again too"
echo "$Person1: I will $BASH you to the stone age again and again and again and again and again and again and again and again"
echo "$Person2: We will $BASH you to the stone age again and again and again and again and again and again and again and again too"
echo "$Person1: I will $BASH you to the stone age again and again and again and again and again and again and