#!/bin/bash
echo "all variables passed to the script are: $@"
echo "number of variables passed to the script are: $#" 
echo "the name of the script is: $0"
echo "the first variable passed to the script is: $1"
echo "the second variable passed to the script is: $2"
echo "the third variable passed to the script is: $3"
echo "the fourth variable passed to the script is: $4"echo "who is running the script: $USER"
echo "the current working directory is: $PWD"
echo "the home directory of the user is: $HOME"
echo "the current shell is: $SHELL"
echo "the current date and time is: $(date)"